### ISSUE TITLE
wm_key_down and wm_sys_key_down not working for me.

### ISSUE THREAD

**Issue by abcjeff** [rodrigocfd/winsafe-examples#3]
Hello,
I'm trying to receive keyboard command on main window, and to receive ESC key and close the window. But when I press keys, events are not captured. Code in closure not running. Here is my code:
```rust
fn events(&self) {
        let self2 = self.clone();
        self.wnd.on().wm_sys_key_down(move |key| {
            self2.txt1.set_text("Syskeydonw");
            println!("key code{}", key.vkey_code);
            Ok(())
        });
        let self2 = self.clone();
        self.wnd.on().wm_key_down(move |key| {
            self2.txt1.set_text("keydown");
            println!("key code{}", key.vkey_code);
            Ok(())
        });
}
```
I've browsed through most examples but can't find an answer.  I also don't know how to exit the event loop and close the window from within a closure. Sorry I'm rather new to Rust and it's my the first time using Winsafe. It's a great project! Thank you.

**Comment by rodrigocfd** [comment]
This is not something WinSafe-specific, it's how Windows behaves.

Once a window has its message loop properly set to work with child controls, the character messages are translated before reaching the window procedure (which dispatches the events we use), so `WM_KEYDOWN` is handled internally, and *some* character messages are translated into [`WM_GETDLGCODE`](https://learn.microsoft.com/en-us/windows/win32/dlgbox/wm-getdlgcode) messages.

Thus, this should work for you:

```rust
fn events(&self) {

  use winsafe::{co, msg};

  self2 = self.clone(); // clone self, so we can use self inside the closure

  self.wnd.on().wm_get_dlg_code(move |p| {
    println!("Key: {}", p.vkey_code);

    if p.vkey_code == co::VK::ESCAPE { // this is the ESC key
      self2.wnd.hwnd().SendMessage(msg::wm::Close {}); // close window
    }

    Ok(co::DLGC::WANTALLKEYS)
  });

}
```

Also, notice how I just sent a [`WM_CLOSE`](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-close) message to close the window. This is the correct way to close a window, because it allows all cleanup to be properly done.

Let me know if this works for you.

**Comment by abcjeff** [comment]
I tested it. Still won't receive keyboard events. here is my full code:
```rust
use winsafe::{prelude::*, gui::{self, Brush}, AnyResult, co::{self, WS}, msg};

#[derive(Clone)]
pub struct MainWin {
	wnd: gui::WindowMain,
    txt1: gui::Edit, 
    txt2: gui::Edit, 
	btn1: gui::Button,     
	btn2: gui::Button,     
}

impl MainWin {
	pub fn new() -> Self {
		let wnd = gui::WindowMain::new( 
			gui::WindowMainOpts {
				title: "TEST".to_owned(),
				size: (470, 150),
                style: WS::POPUP | WS::VISIBLE,
                class_bg_brush: Brush::Color(co::COLOR::BACKGROUND),
				..Default::default() 
			}, 
		);
        let txt1 = gui::Edit::new(&wnd,gui::EditOpts {position:(10, 10),width:450,..Default::default()},);
        let txt2 = gui::Edit::new(&wnd,gui::EditOpts {position:(10, 38),width:450,..Default::default()},);
		let btn1 = gui::Button::new(&wnd,gui::ButtonOpts {text:"Button1".to_owned(),position:(10, 70),..Default::default()},);
		let btn2 = gui::Button::new(&wnd,gui::ButtonOpts {text:"Close".to_owned(),position:(100, 70),..Default::default()},);
        
		let new_self = Self { wnd, txt1, txt2, btn1, btn2 };
		new_self.events(); 
		new_self
	}

	pub fn run(&self) -> AnyResult<i32> {
		self.wnd.run_main(None) 
	}

	fn events(&self) {
        let self2 = self.clone();
		self.btn1.on().bn_clicked(move || { 
            let text = self2.txt1.text();
            self2.txt2.set_text(&text);
            self2.txt2.focus();
            self2.txt2.set_selection(Some(0), Some(text.len() as u32));
			Ok(())
		});
        let self2 = self.clone();
		self.btn2.on().bn_clicked(move || { 
            self2.wnd.hwnd().SendMessage(msg::wm::Close {});
			Ok(())
		});
	let self2 = self.clone();
	self.wnd.on().wm_get_dlg_code(move |p| {
		println!("Key: {}", p.vkey_code);
		if p.vkey_code == co::VK::ESCAPE { // this is the ESC key
		self2.wnd.hwnd().SendMessage(msg::wm::Close {}); // close window
		}
		Ok(co::DLGC::WANTALLKEYS)
		});
	}
}

fn main() {
	MainWin::new().run().unwrap();
}
```
My main window is a popup style. Nothing happens when I press ESC. Everything else works fine including closing window with WM_CLOSE message (When I click button2). I have only this one file in my project besides cargo.toml.  Could you test it for me. Thank you so much!

**Comment by rodrigocfd** [comment]
If you have controls in your window, it doesn't have the focus anymore, and the **controls** are processing the char messages. So... things are [a bit more complicated](https://stackoverflow.com/a/64814749/6923555).

For the ESC key, however, there is a trick you can use.

The [`IsDialogMessage`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-isdialogmessagew) function, which called internally in the window loop, actually translates the ESC key into a [`WM_COMMAND`](https://learn.microsoft.com/en-us/windows/win32/menurc/wm-command) message, which you can easily handle:

```rust
let self2 = self.clone();
self.wnd.on().wm_command_accel_menu(co::DLGID::CANCEL.into(), move || { // ESC key
	self2.wnd.hwnd().SendMessage(msg::wm::Close {}); // close window
	Ok(())
});
```

**Comment by abcjeff** [comment]
Wow this trick really works! Thank you. 👍
