### ISSUE TITLE
Open file dialog example

### ISSUE THREAD

**Issue by shraik** [rodrigocfd/winsafe-examples#7]
Hi,
Can you help me with "open file dialog" example ?

**Comment by rodrigocfd** [comment]
Didn't the [example in the docs](https://rodrigocfd.github.io/winsafe/winsafe/struct.IFileOpenDialog.html) work for you?

**Comment by shraik** [comment]
I don't understand how to use it.
how to call correctly and where to get hparent ?
error[E0521]: borrowed data escapes outside of method
"`self` escapes the method body "
[my_window.zip](https://github.com/rodrigocfd/winsafe-examples/files/15281742/my_window.zip)

**Comment by rodrigocfd** [comment]
> I didn’t immediately understand where to get hparent, but I figured it out.

I don't know your experience with Rust, but looking at your code, you seem to lack the understanding of [associated constants](https://doc.rust-lang.org/reference/items/associated-items.html#associated-constants). You can just do:

```rust
file_open.Show(&HWND::NULL)
```
